### ISSUE TITLE
VueJS 3.4.16 broke dropdown

### ISSUE THREAD

**Issue by te-deum** [SuadeLabs/vue3-multiselect#12]
Hello,

I am using this plugin for a project and when I upgrade Vue with NPM from 3.4.15 to the 3.4.16, the plugin doesn't work anymore.
In fact the dropdown list does'nt popup anymore on click.

Revert VueJS to 3.4.15 solve the problem.

I hope it can be fixed.
Regards.

**Comment by mattelen** [comment]
This occurred due to a bug in VueJS (https://github.com/vuejs/core/issues/10294). As you can see from the changelog, they have reverted and fixed this issue in versions released since: https://github.com/vuejs/core/blob/main/CHANGELOG.md

So, if you (or anyone else) encounter this issue, please update your version of Vue
